Algoritmo "contador"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/04/2024
Var
contador1,contador2:inteiro
Inicio
contador1 <-1
contador2 <-10
Enquanto contador1<=5 faça
Escreva ("contador 1 ",contador1,"-contador 2:", contador2)
contador1<- contador1 +1
contador2 <-contador2-1
FimEnquanto


Fimalgoritmo