Algoritmo "idade"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : barbosa
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    :julia
// Data atual  : 30/04/2024
Var
idade:inteiro


Inicio
escreva ("Digite a sua idade:")
leia (idade)
se (idade>=18) entao
escreval("maior de idade")
senao
escreval(idade,"anos idade")
escreval("considerando menor de idade")
fimse

Fimalgoritmo